#!/usr/bin/python

USAGE = ('Usage:\n'
         '    pixiclock-client message message ...\n'
         '    pixiclock-client -p PORT message message ...')

from socket import socket
from sys import argv, stdin
from getopt import getopt, GetoptError

def main():

    port = 7070

    try:
        opts, args = getopt(argv[1:], 'p:')
        for o, v in opts:
            port = int(v)
        if len(args) == 0:
            args.append(stdin.read())
    except GetoptError, e:
        print str(e)
        print USAGE
        return            
    except Exception, e:
        print '%s: %s' % (str(e.__class__), str(e))
        return

    for data in args:
        s = socket()
        s.connect(('localhost', port))
        while data:
            n = s.send(data)
            data = data[n:]
        s.close()
        
if __name__ == '__main__':
    main()
